import { Project } from "../types";

export const PROJECTS: Project[] = [
  {
    title: "AI ChatBot",
    tag: "WEB & MOBILE APP",
    description: "Intelligent conversational agent with context-aware natural language processing.",
    tech: ["NEXT.JS", "OPENAI API", "TAILWIND CSS"],
    impact: "Automated 80% of tier-1 support queries with a 95% satisfaction rate.",
    featured: true,
    color: "#5C6BC0",
    category: "AI/ML",
    stars: 210,
    forks: 85,
    id: "ChatBot",
    mockups: {
      desktop: "/images/chatbot/desktop.png",
      mobile: "/images/chatbot/mobile.png"
    }
  },
  {
    title: "DuriooAI",
    tag: "WEB PLATFORM",
    description: "Generative AI platform designed to enhance creative workflows and content generation.",
    tech: ["REACT", "NODE.JS", "PYTHON"],
    impact: "Streamlined content creation processes, reducing production time by 40%.",
    featured: true,
    color: "#E91E63",
    category: "Web Development",
    stars: 89,
    forks: 21,
    id: "DuriooAI",
    mockups: {
      desktop: "/images/duriooai/desktop.png"
    }
  },
  {
    title: "Duri Image Gen",
    tag: "MOBILE APP",
    description: "Mobile application for generating on-device AI art using optimized diffusion models.",
    tech: ["REACT NATIVE", "TENSORFLOW LITE", "PYTHON"],
    impact: "Achieved sub-2s generation time for 512x512 images on standard mobile hardware.",
    featured: true,
    color: "#AA00FF",
    category: "AI/ML",
    stars: 342,
    forks: 115,
    id: "DuriImageGen",
    mockups: {
      mobile: "/images/duri-image-gen/mobile-center.png",
      mobileLeft: "/images/duri-image-gen/mobile-left.png",
      mobileRight: "/images/duri-image-gen/mobile-right.png"
    }
  },
  {
    title: "DuriooGPT",
    tag: "WEB & MOBILE APP",
    description: "Kids-friendly safe AI language model platform with educational capabilities and storytelling generation.",
    tech: ["NEXT.JS", "REACT NATIVE", "LLM", "AWS"],
    impact: "Built a fully safe conversational engine for 500k+ young users.",
    featured: true,
    color: "#FF5252",
    category: "AI/ML",
    stars: 567,
    forks: 112,
    id: "DuriooGPT",
    mockups: {
      desktop: "/images/durioogpt/desktop.png",
      mobile: "/images/durioogpt/mobile.png"
    }
  },
  {
    title: "Rotoscope",
    tag: "VIDEO TOOL",
    description: "Automated rotoscoping pipeline that isolates subjects from video backgrounds using AI-driven segmentation.",
    tech: ["PYTHON", "OPENCV", "PYTORCH", "FFMPEG"],
    impact: "Reduced manual rotoscoping time by 90% for production-level video assets.",
    featured: false,
    color: "#00BCD4",
    category: "Video Production",
    stars: 98,
    forks: 27,
    id: "Rotoscope"
  },
  {
    title: "Motion Graphics",
    tag: "VIDEO TOOL",
    description: "Templated motion graphics engine for generating branded animated sequences programmatically.",
    tech: ["AFTER EFFECTS", "PYTHON", "JAVASCRIPT", "SVG"],
    impact: "Cut animated asset delivery time from days to hours across multiple campaigns.",
    featured: false,
    color: "#FF9800",
    category: "Video Production",
    stars: 74,
    forks: 18,
    id: "MotionGraphics"
  },
  {
    title: "AI Content",
    tag: "AI TOOL",
    description: "End-to-end AI-powered content pipeline for script generation, image creation, and copy optimisation.",
    tech: ["OPENAI API", "LANGCHAIN", "NEXT.JS", "PYTHON"],
    impact: "Accelerated content output by 5× while maintaining brand voice consistency.",
    featured: false,
    color: "#8BC34A",
    category: "AI/ML",
    stars: 132,
    forks: 41,
    id: "AIContent"
  },
  {
    title: "Aurat Intelligence",
    tag: "AI PLATFORM",
    description: "Modesty-aware computer vision system that detects and flags non-compliant content in media pipelines.",
    tech: ["PYTORCH", "YOLO", "FASTAPI", "REACT"],
    impact: "Achieved 97% detection accuracy, enabling safer content moderation at scale.",
    featured: true,
    color: "#9C27B0",
    category: "AI/ML",
    stars: 187,
    forks: 52,
    id: "AuratIntelligence"
  },
  {
    title: "Intro Remover",
    tag: "VIDEO TOOL",
    description: "Intelligent tool that automatically detects and removes fixed intro sequences from video batches.",
    tech: ["PYTHON", "FFMPEG", "OPENCV", "ML"],
    impact: "Processed thousands of episodes automatically, saving hundreds of hours of manual editing.",
    featured: false,
    color: "#F44336",
    category: "Video Production",
    stars: 63,
    forks: 14,
    id: "IntroRemover"
  },
  {
    title: "Watermark The Videos",
    tag: "VIDEO TOOL",
    description: "Batch video watermarking service with dynamic positioning, opacity control, and brand presets.",
    tech: ["PYTHON", "FFMPEG", "PILLOW", "FASTAPI"],
    impact: "Watermarked 10,000+ videos in automated daily runs with zero manual intervention.",
    featured: false,
    color: "#607D8B",
    category: "Video Production",
    stars: 45,
    forks: 11,
    id: "WatermarkTheVideos"
  },
  {
    title: "Video Analyzer",
    tag: "AI TOOL",
    description: "AI-driven video analysis tool that extracts metadata, scenes, sentiment, and content insights from video files.",
    tech: ["PYTHON", "GEMINI API", "FFMPEG", "FASTAPI"],
    impact: "Enabled data-driven editorial decisions by surfacing deep content insights automatically.",
    featured: false,
    color: "#3F51B5",
    category: "AI/ML",
    stars: 109,
    forks: 33,
    id: "VideoAnalyzer"
  },
  {
    title: "VocalOnly Generator",
    tag: "AUDIO TOOL",
    description: "Source-separation pipeline that isolates clean vocal tracks from mixed audio or video for post-production.",
    tech: ["PYTHON", "DEMUCS", "FFMPEG", "FASTAPI"],
    impact: "Delivered studio-quality vocal stems in seconds, replacing expensive manual stem production.",
    featured: false,
    color: "#00ACC1",
    category: "Audio/Video",
    stars: 88,
    forks: 22,
    id: "VocalOnlyGenerator"
  },
  {
    title: "Subtitle Generator",
    tag: "AI TOOL",
    description: "Automatic multilingual subtitle generation and embedding tool powered by speech recognition models.",
    tech: ["WHISPER", "PYTHON", "FFMPEG", "REACT"],
    impact: "Generated accurate subtitles for 1000+ videos, boosting content accessibility across platforms.",
    featured: false,
    color: "#43A047",
    category: "AI/ML",
    stars: 154,
    forks: 47,
    id: "SubtitleGenerator"
  },
  {
    title: "Compilation Generator",
    tag: "VIDEO TOOL",
    description: "Automated pipeline for assembling themed video compilations from a library of clips based on metadata tags.",
    tech: ["PYTHON", "FFMPEG", "PANDAS", "FASTAPI"],
    impact: "Produced weekly compilation series at zero manual cost, growing channel watch time by 35%.",
    featured: false,
    color: "#FB8C00",
    category: "Video Production",
    stars: 57,
    forks: 15,
    id: "CompilationGenerator"
  },
  {
    title: "Durioo Wrapped",
    tag: "WEB APP",
    description: "Annual personalised viewing-recap experience for Durioo users, surfacing their top shows, characters, and stats.",
    tech: ["NEXT.JS", "POSTGRESQL", "FRAMER MOTION", "AWS"],
    impact: "Drove a 60% social share rate and boosted platform re-engagement during the campaign period.",
    featured: true,
    color: "#E53935",
    category: "Web Development",
    stars: 201,
    forks: 58,
    id: "DuriooWrapped"
  },
  {
    title: "Durioo IP Gems",
    tag: "WEB PLATFORM",
    description: "Internal IP asset management platform for cataloguing, tagging, and licensing Durioo's content properties.",
    tech: ["REACT", "NODE.JS", "POSTGRESQL", "S3"],
    impact: "Centralised 500+ IP assets, reducing content retrieval time by 70% across departments.",
    featured: false,
    color: "#FFB300",
    category: "Web Development",
    stars: 76,
    forks: 19,
    id: "DuriooIPGems"
  },
  {
    title: "n8n Automation Solution",
    tag: "AUTOMATION",
    description: "End-to-end workflow automation solutions built on n8n, integrating CRMs, APIs, and internal tools seamlessly.",
    tech: ["N8N", "NODE.JS", "REST APIs", "WEBHOOKS"],
    impact: "Automated 30+ operational workflows, recovering 200+ man-hours per month.",
    featured: false,
    color: "#EA4B71",
    category: "Automation",
    stars: 93,
    forks: 28,
    id: "N8nAutomation"
  },
  {
    title: "BraveGemini News",
    tag: "AI TOOL",
    description: "AI-curated news aggregator that summarises and fact-checks trending articles using the Gemini API.",
    tech: ["GEMINI API", "NEXT.JS", "NODE.JS", "POSTGRESQL"],
    impact: "Delivered daily AI-summarised briefings to subscribers with 90%+ relevance ratings.",
    featured: false,
    color: "#FF7043",
    category: "AI/ML",
    stars: 118,
    forks: 36,
    id: "BraveGeminiNews"
  },
  {
    title: "Mobile App Dev",
    tag: "MOBILE APP",
    description: "Cross-platform mobile application development spanning consumer apps, internal tools, and AI-integrated experiences.",
    tech: ["REACT NATIVE", "EXPO", "FIREBASE", "NODE.JS"],
    impact: "Shipped multiple apps with combined 50k+ installs and 4.7★ average store rating.",
    featured: true,
    color: "#26C6DA",
    category: "Mobile Development",
    stars: 245,
    forks: 71,
    id: "MobileAppDev"
  }
];
